/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from './Ownable';
export type { FacuetMock } from './FacuetMock';

export { Ownable__factory } from './factories/Ownable__factory';
export { FacuetMock__factory } from './factories/FacuetMock__factory';
